config/routes.rb
Stock::Application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resource :sessions, only: [:new, :create]
  resources :users

  get 'tags/:tag', to: "items#index", as: :tag
  root to: 'items#index'
  resources :tags, only: [:index]
  resources :items, except: [:show]
end

app/models/concerns/taggable.rb
module Taggable
  extend ActiveSupport::Concern

  included do
    attr_accessible :tag_list
    has_many :taggings
    has_many :tags, through: :taggings
  end

  module ClassMethods

    def tagged_with(name)
      name.present? ? Tag.find_by_name!(name).items : self
    end

    def tag_counts
      Tag.select("tags.id, tags.name, count(taggings.tag_id) as count").
          joins(:taggings).group("taggings.tag_id, tags.id, tags.name")
    end
  end

  def tag_list
    tags.map(&:name).join(", ")
  end

  def tag_list=(names)
    self.tags = names.split(",").map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  include Taggable

  belongs_to :user

  attr_accessible :name, :quantity, :user_id
  validates :name, presence: true

  default_value_for :quantity, 1

  def none?
    quantity < 0
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :taggings
  has_many :items, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :item
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::ForbiddenAttributesProtection
  has_many :items

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 8, if: ->(u) { u.password.present? } }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/items_controller.rb
# -*- coding: utf-8 -*-
class ItemsController < ApplicationController
  before_filter :authorize

  def index
    @q = current_user.items.search(params[:q])
    #    @q.sorts = "quantity asc"
    @q.sorts = "id desc"
    @items = @q.result.all
#    @items = @q.result.tagged_with(params[:tag]).all
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = current_user.items.build(params[:item])
##    @item = Item.new(params[:item])

    if @item.save
      redirect_to items_path, notice: 'アイテムを追加しました'
    else
      render action: "new"
    end
  end

  def update
    @item = current_user.items.find(params[:id])
#    @item = Item.find(params[:id])

    if @item.update_attributes(params[:item])
      redirect_to items_path, notice: 'アイテムを更新しました'
    else
      render action: "edit"
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
#    @item = Item.find(params[:id])
    @item.destroy

    redirect_to items_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :authorize, only: [:show]

  def new; end

  def show; end

  def create
    auth = Authentication.new(params)
    if auth.authenticated?
      session[:user_id] = auth.user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Username or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :authorize

  def index
    @tags = Tag.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud(tags, classes)
    max = 0
    tags.each do |t|
      if t.count.to_i > max
        max = t.count.to_i
      end
    end
    tags.each do |tag|
      index = tag.count.to_f / max * (classes.size - 1)
      yield(tag, classes[index.round])
    end
  end

  def flash_notifications
    message = flash[:error] || flash[:notice]

    if message
      type = flash.keys[0].to_s
      javascript_tag %Q{$.notification({ message:"#{message}", type:"#{type}" });}
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/items/_form.html.erb
<% content_for :error do %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= form_for(@item, html: { data: { ajax: "false"}} ) do |f| %>

  <fieldset>
    <div data-role="fieldcontain">
      <%= f.label :name, "品名" %>
      <%= f.text_field :name, placeholder: "トイレットペーパー" %>
    </div>
    
    <div data-role="fieldcontain">
      <%= f.label :tag_list, "場所(カンマ区切り)" %>
      <%= f.text_field :tag_list %>
    </div>
    
    <div data-role="fieldcontain">
      <%= f.label :quantity, "数", data: {inline: "true" } %>
      <%= f.number_field :quantity, maxlength: 5, data: { highlight: "true", inline: "true" }, style: "width: 45px; display: inline-block"  %>
      <%= link_to "Plus", "#",  id: "quantity_plus", data: { role: "button", icon: "plus", iconpos: "notext", inline: "true" } %>
      <%= link_to "Minus", "#",  id: "quantity_minus", data: { role: "button", icon: "minus", iconpos: "notext", inline: "true" } %>
    </div>

    <%= f.submit "保存" %>
  </fieldset>
<% end %>

app/views/items/edit.html.erb
<% content_for :heading do %>
  <%= link_to '一覧', items_path, data: {icon: "back"} %>
  <h1><%= @item.name %></h1>
  <%= link_to 'Delete', @item, method: "delete", confirm: "削除してもよろしいですか?", data: {icon: "delete"} %>
<% end %>

<%= render 'form' %>

app/views/items/index.html.erb
<% content_for :heading do %>
  <a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
  <h1>在庫一覧</h1>
  <%= link_to 'New', new_item_path, "data-icon" => "plus" %>
<% end %>

<ul data-role="listview" data-filter="true">
  <% @items.each do |item| %>
    <%= content_tag(:li, data: { theme: item.none? ? "e" : "c" }) do %>
      <%= link_to edit_item_path(item) do %>
        <%= item.name %>
        <small>(<%= item.tags.map(&:name).join(', ') %>)</small>
        <span class="ui-li-count">
          <%= item.quantity %>
        </span>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/items/new.html.erb
<% content_for :heading do %>
  <%= link_to '一覧', items_path, data: {icon: "back"} %>
  <h1>追加</h1>
<% end %>

<%= render 'form' %>

app/views/items/show.html.erb
<% content_for :heading do %>
  <%= link_to 'Back', :back, data: {icon: "back"} %>
  <h1><%= @item.name %></h1>
  <%= link_to 'Delete', @item, method: "delete", data: {icon: "delete"} %>
<% end %>

<h2><%= @item.name %></h2>

<% @item.tags.each do |tag| %>
  <%= link_to tag.name, tag_path(tag.name) %>  
<% end %>


<%= @item.quantity %>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Stock</title> 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>

	<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
  <%= csrf_meta_tags %>
</head> 

<body>

  <div data-role="page">

    <div data-role="panel" data-position-fixed="true" data-theme="a" id="nav-panel">
      <ul data-role="listview" data-theme="a" class="nav-search">
        <li data-icon="delete"><a href="#" data-rel="close">メニューを閉じる</a></li>
        <li><%= link_to "在庫一覧", items_path, {data: {ajax: false}}  %></li>
        <li><%= link_to "タグ一覧", tags_path, {data: {ajax: false}} %></li>
        <li><%= link_to "ログアウト", logout_path, {data: {ajax: false}} %></li>
      </ul>
    </div><!-- /panel -->

    <div data-role="header" data-position="fixed">
      <%= yield :heading %>
    </div>

    <%= flash_notifications %>

    <div data-role="content">
      <%= yield %>
    </div>


    <div data-role="navbar" data-position="fixed">
      <ul>
        <li>
          <%= link_to "在庫", items_path %>
        </li>
        <li>
          <%= link_to "タグ", tags_path %>
        </li>
      </ul>
    </div>
  </div>
</body>
</html>

app/views/tags/index.html.erb
<% content_for :heading do %>
  <a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
  <h1>タグ一覧</h1>
<% end %>

<ul data-role="listview" data-filter="true">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag_path(tag.name) do %>
        <%= tag.name %>
        <span class="ui-li-count">
          <%= tag.items.size %>
        </span>
      <% end %>
    </li>
  <% end %>
</ul>